Feature: Webhook REST Related Tests

  # @author cryan@redhat.com
  Scenario Outline: Trigger build with webhook
    Given I have a project
    And I process and create "https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/build/ruby20rhel7-template-sti.json"
    Given the "ruby-sample-build-1" build completes
    When I run the :patch client command with:
      | resource | buildconfig |
      | resource_name | ruby-sample-build |
      | p | {"spec": {"triggers": [{"type": "<type>","<type>": {"secret": "secret101"}}]}} |
    Then the step should succeed
    When I run the :describe client command with:
      | resource | buildconfig |
      | name | ruby-sample-build |
    Then the output should not contain "<negative1>"
    Then the output should not contain "<negative2>"
    Given I download a file from "https://raw.githubusercontent.com/openshift/origin/master/pkg/build/webhook/<path><file>"
    And I replace lines in "<file>":
      | 9bdc3a26ff933b32f3e558636b58aea86a69f051 ||
    When I perform the HTTP request:
    """
    :url: <%= env.api_endpoint_url %>/oapi/v1/namespaces/<%= project.name %>/buildconfigs/ruby-sample-build/webhooks/secret101/<type>
    :method: post
    :headers:
      :Content-Type: application/json
      :<header1>: <header2>
    :payload: <%= File.read("<file>").to_json %>
    """
    Then the step should succeed
    Given the "ruby-sample-build-2" build was created
    Given the "ruby-sample-build-2" build completes
    Given a pod becomes ready with labels:
      | deployment=frontend-2 |
    When I perform the HTTP request:
    """
    :url: <%= env.api_endpoint_url %>/oapi/v1/namespaces/<%= project.name %>/buildconfigs/ruby-sample-build/webhooks/secret101/<negative3>
    :method: post
    :headers:
      :Content-Type: application/json
    :payload: <%= File.read("<file>").to_json %>
    """
    Then the step should fail
    Then the output should contain "not accept"
    Examples:
      | type    | negative1 | negative2   | negative3 | path              | file              | header1        | header2 |
      | generic | GitHub    | ImageChange | github    | generic/testdata/ | push-generic.json |                |         | # @case_id OCP-11693
      | github  | Generic   | ImageChange | generic   | github/testdata/  | pushevent.json    | X-Github-Event | push    | # @case_id OCP-11875

  # @author cryan@redhat.com
  # @case_id OCP-11270
  Scenario: OCP-11270 New parameter can be passed via generic webhook
    Given I have a project
    When I run the :new_app client command with:
      | file | https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/build/ruby22rhel7-template-sti.json |
    Then the step should succeed
    When I run the :patch client command with:
      | resource | buildconfig |
      | resource_name | ruby22-sample-build |
      | p | {"spec": {"triggers": [{"type": "Generic","generic": {"secret": "secret101","allowEnv": true}}]}} |
    Then the step should succeed
    #Cancel the first build to speed up the second generated by the webhook
    Given the "ruby22-sample-build-1" build becomes :running
    When I run the :cancel_build client command with:
      | build_name | ruby22-sample-build-1 |
    Then the step should succeed
    Given I download a file from "https://raw.githubusercontent.com/openshift/origin/master/pkg/build/webhook/generic/testdata/push-generic-envs.json"
    And I replace lines in "push-generic-envs.json":
      | 9bdc3a26ff933b32f3e558636b58aea86a69f051 ||
      | EXAMPLE    | TEST  |
      | sample-app | valid |
    When I perform the HTTP request:
    """
    :url: <%= env.api_endpoint_url %>/oapi/v1/namespaces/<%= project.name %>/buildconfigs/ruby22-sample-build/webhooks/secret101/generic
    :method: post
    :headers:
      :content-type: application/json
      :openshift: generic
    :payload: <%= File.read("push-generic-envs.json").to_json %>
    """
    Then the step should succeed
    Given the "ruby22-sample-build-2" build becomes :running
    When I run the :describe client command with:
      | resource | pod                         |
      | name     | ruby22-sample-build-2-build |
    Then the step should succeed
    And the output should contain:
      | TEST  |
      | valid |
      | EXAMPLE    |
      | sample-app |

