= How to implement upgrade testing

== Overview

Upgrade testing means creating services and other resources in an OpenShift
cluster, then upgrading cluster to a newer version and verifying that
all resources are still working properly.

The keys here are to:

* avoid clean-up after/before scenarios
* use same usernames in the `prepare` and `check` phases

We achieve this using a special user manager `UpgradeUserManager`.

== Writing scenarios

It is possible to use different approaches. See bullet points for one such approach:

* Write two test scenarios - one for preparing resources and one for checking after upgrade.
* Name of scenarios would be the same except that `prepare` scenario will have suffix like `my scenario name - prepare`.
* Use tag `@upgrade-prepare` for `prepare` scenarios and tag `@upgrade-check` for `check` scenarios.
* Set tag for each scenario `@users=upuser1,upuser2,upuserN` where you make sure scenarios would not have interfering users. These are only symbolic users.
* you can see example upgrade scenarios in `features/test/upgrade.feature`.

== Running the tests

The main points for running upgrade test scenarios are:

* Set `OPENSHIFT_ENV_<ENV NAME>_USER_MANAGER=UpgradeUserManager`
* Set symbolic user to actual cluster user mapping (in `config.yaml` or `BUSHSLICER_CONFIG`)

[source,yaml]
----
environments:
  ocp4:
    static_users_map:
      upuser1: "upg1:pswd1"
      upuser2: "upg2:pswd2"
      upuser3: "upg3:pswd3"
----

* select test cases for execution

You can always select test cases in the usual way

----
$ cucumber features/upgrade/projects.feature --tags @upgrage_prepare
----

If you are using a test case management system though, you can select scenarios
like

----
$ export POLARSHIFT_TEST_CASE_NAME_SUFFIX=" - prepare"
$ TCMS_SPEC=run:my-test-run-name cucumber -p polarshift --tags @upgrade-prepare
## now upgrade cluster
$ unset POLARSHIFT_TEST_CASE_NAME_SUFFIX
$ TCMS_SPEC=run:my-test-run-name cucumber -p polarshift --tags @upgrade-check
----

=== Sample commands to run check and prepare phases

Now example with all commands needed to run upgrade tests

[source,bash]
----
$ export BUSHSLICER_DEFAULT_ENVIRONMENT=ocp4
$ export OPENSHIFT_ENV_OCP4_USER_MANAGER=UpgradeUserManager
$ export OPENSHIFT_ENV_OCP4_ADMIN_CREDS_SPEC='https://www.example.com/my/admin/kubeconfig'
$ export OPENSHIFT_ENV_OCP4_HOSTS=api.example.com:lb
$ export BUSHSLICER_CONFIG='
  environments:
    ocp4:
      static_users_map:
        upuser1: "upg1:pswd1"
        upuser2: "upg2:pswd2"
        upuser3: "upg3:pswd3"
'
$ export POLARSHIFT_TEST_CASE_NAME_SUFFIX=" - prepare"
$ TCMS_SPEC=run:my-prepare-test-run-name cucumber -p polarshift --tags @upgrade-check

### now you upgrade the cluster

$ unset POLARSHIFT_TEST_CASE_NAME_SUFFIX
$ TCMS_SPEC=run:my-check-test-run-name cucumber -p polarshift --tags @upgrade-check
----
