eval File.read(File.expand_path(__FILE__ + "/../../Gemfile")), binding, "../Gemfile"

gem 'asciidoctor'
gem 'commander'
gem 'text-table'
gem 'stomp'
gem 'jenkins_api_client'
gem 'mize'
gem 'ansicolor'
